---
netbird_management_url: "{{ lookup('pipe', 'op read \"op://Private/NetBirdPi/url\"') }}"
netbird_setup_key: "{{ lookup('pipe', 'op read \"op://Private/NetBirdPi/credential\"') }}"
netbird_allow_ssh: true
netbird_allow_ssh_root: true
