apiVersion: v1
kind: Secret
metadata:
  name: forgejo-credentials
type: Opaque
stringData:
  FORGEJO_ADMIN_USER: admin
  FORGEJO_ADMIN_PASSWORD: changeme-use-sops
  FORGEJO_ADMIN_EMAIL: admin@example.com
